# Generated by Django 5.0.1 on 2024-02-11 18:08

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0002_remove_customuser_id_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "post_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post_images")),
                ("created_time", models.DateTimeField(default=datetime.datetime.now)),
                ("number_of_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
